### PR TITLE
meta.yaml: update recipe-maintainers

### PR DESCRIPTION
**Pull request by veghdev**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by veghdev** [comment]
@conda-forge-admin, please rerender

**Comment by veghdev** [comment]
@sugatoray "Ensured the license file is being packaged." This means that meta.yaml contains the following lines?
about:
  license: Apache-2.0
  license_file:
    - LICENSE

**Comment by sugatoray** [comment]
Hi @veghdev,

This means:

- either the license file is packaged in the source from PyPI
- or, it is separately available inside the recipe folder as a separate file

The set of key-value parameters under the `about` section in the `meta.yaml` file is a mere reference to where to find the license. It will not work unless the file is already available while building the conda-forge package. 

👉 In this case, the source (`*.tar.gz`) from PyPI already contains the LICENSE file.

**Comment by sugatoray** [comment]
@veghdev Please see my comments.

**Comment by veghdev** [comment]
> @veghdev Please see my comments.

@sugatoray I read all your comments, maybe I missed something?

**Comment by sugatoray** [comment]
I left a suggestion to add a comment in the meta.yaml file. Could you please add the suggestion?

**Comment by sugatoray** [comment]
Also, I am planning on hosting a conda-forge recipe creators workshop in near future. Would you like to attend a hands on workshop?

Please feel free to respond to this poll and share it with anyone else you might think could benefit from the workshop. 

https://www.linkedin.com/posts/sugatoray_conda-condaforge-workshop-activity-6962057281697984512-u7yM

**Comment by veghdev** [comment]
@conda-forge-admin, please rerender

**Comment by veghdev** [comment]
@sugatoray I placed a comment

**Comment by sugatoray** [comment]
@veghdev I added you via another PR. I am a little short of time now. I am closing this PR. But please see my comment next to the comment you wanted to add. The workshop I intend to organize will go over why it's better not to have comments in the same line.

If I somehow forget that, and you attend the workshop, please remind me.

**Comment by veghdev** [comment]
> @veghdev I added you via another PR. I am a little short of time now. I am closing this PR. But please see my comment next to the comment you wanted to add. The workshop I intend to organize will go over why it's better not to have comments in the same line.
> 
> If I somehow forget that, and you attend the workshop, please remind me.

Thanks, I misunderstood you about the comment, I checked it.

**Pull request closed without merging**
