### PR TITLE
README: update Feedstock Maintainers

### PR DESCRIPTION
**Pull request by veghdev**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@sugatoray Please add me (from Vizzu team) into Feedstock Maintainers. Thanks.

### CODE REVIEW

**Comment by sugatoray** [comment]
@veghdev Have you maintained any conda-forge package before or authored any new recipe to add any PyPI package to conda-forge before?

If not, I would prefer to walk you through a few things first, before adding you as a maintainer. 

Also, the README is autogenerated. We must never update the README. 

What I would suggest is that you send a PR to this repository and update the recipe (`meta.yaml` file). If you have any questions there, I will be glad to help you out. 

For now I am closing this PR. Let's get you acquainted with how to update the package here and maintain the recipe first.

**Comment by veghdev** [comment]
> @veghdev Have you maintained any conda-forge package before or authored any new recipe to add any PyPI package to conda-forge before?
> 
> If not, I would prefer to walk you through a few things first, before adding you as a maintainer.
> 
> Also, the README is autogenerated. We must never update the README.
> 
> What I would suggest is that you send a PR to this repository and update the recipe (`meta.yaml` file). If you have any questions there, I will be glad to help you out.
> 
> For now I am closing this PR. Let's get you acquainted with how to update the package here and maintain the recipe first.

@sugatoray Thank you. I am not experienced in conda yet, but I am going to read about it :)
I got it, I will edit the meta.yaml.
I would like to join as a maintainer to keep the description up to date, approve auto PR-s when we release new version etc.

**Comment by sugatoray** [comment]
@veghdev Auto PRs typically, if ran successfully, get merged automatically (by another bot). So, maintainers need not work on that. 

But when the dependencies change, sometimes (or, often, depending on the stage of the library's development) manually fixing the recipe becomes necessary. 

I am glad that you would like to maintain the feedstock. This is very much appreciated. But, this does not need you to be a maintainer in the first place. A PR to the feedstock will also suffice. 

In my experience, adding upstream repo contributors as maintainers of the feedstock did not often work out effectively, if they already did not have enough experience with updating/maintaining conda-forge packages. 

So, while I maintain over 60 feedstocks and it's a blessing when people show interest in co-maintaining the feedstocks, unless the volunteers are properly empowered with some practical experience of how to maintain the feedstocks, such collaborations did not effectively work as most often they would only remain as dormant maintainers. 

So, I would like to add you as a maintainer, once we have at least worked with one-two such update cycles. 

I can help you learn the ropes, if you are willing to. But merely adding you as a maintainer, will not help until you can create new conda-forge recipes if necessary (this is often needed). 

If you are open to letting me help you create the recipe file when the next update happens, let's set up a meeting session and show you what is necessary in a live session.

**Comment by veghdev** [comment]
@sugatoray Thanks, I appreciate your help and understand your concerns.
I would like to actively participate in the maintenance as I do with our other Vizzu packages.
However I have little experience with conda, so I would be very grateful if you could review this at the beginning.
Of course you can keep our maintenance PR-s open until we work together.
Furthermore I think it would be an advantage that someone from Vizzu has access (but only after your worries are gone).

**Comment by sugatoray** [comment]
@veghdev Thank you for understanding. I look forward to adding you as a co-maintainer to both `ipyvizzu` and `ipyvizzu-story` feedstocks. And thank you for offering to co-maintain. 

Yes, it is the ideal solution to have someone from the upstream repository to have on the list of maintainers for the conda-forge feedstock. 🚀

**Pull request closed without merging**
